name: CI - Playwright MCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-mcp-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
            npm ci
            sleep 5

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Generate tests from prompts
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
            echo "Running MCP server to generate tests"
            npm run mcp:run

      - name: List generated tests (debug)
        run: |
            if [ -d "generated-tests" ]; then
            echo "Generated tests:"
            ls -la generated-tests
            else
            echo "No generated tests directory found"
            fi

      - name: Run generated tests
        run: npm test

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/